### ISSUE TITLE
[Suggestion] - Win10 Debloat - Security Settings

### ISSUE THREAD

**Issue by angry-bender** [digitalsleuth/winfor-salt#8]
Hey Mate,

Just making a suggestion for the debloat script on this one to leave windows defender and windows firewall as is. As i think that should be a concious decision by the end user :-).

I do note it can just be uncommented, but its still something I'd prefer to make obvious, particuarly if you accidentally detonate malz on your forensics machine

**Comment by digitalsleuth** [comment]
This is a good point, however AV won't protect you from detonating malware on your computer if you can't get it on your computer anyways with AV enabled :) Because of the nature of some of the tools, I have the debloat set to disable AV first, then install the tools (a few of which Defender sees as hacktools - ie: mimikatz, OfficeMalScanner, etc). Once everything is installed, there's nothing stopping the end user from re-enabling it though. 

I'll give it some thought, and check the impact if enabled first. I'll keep this suggestion open while I review.

Cheers!

**Comment by angry-bender** [comment]
> This is a good point, however AV won't protect you from detonating malware on your computer if you can't get it on your computer anyways with AV enabled :) Because of the nature of some of the tools, I have the debloat set to disable AV first, then install the tools (a few of which Defender sees as hacktools - ie: mimikatz, OfficeMalScanner, etc). Once everything is installed, there's nothing stopping the end user from re-enabling it though. 
> 
> I'll give it some thought, and check the impact if enabled first. I'll keep this suggestion open while I review.
> 
> Cheers!

All good, I'm assuming it will also false positive things like sigma rules. Could be good to change the defender config to an exclusion path instead, and include that in the doco

**Comment by digitalsleuth** [comment]
I've been setting paths for those actually, I just have to make sure that everything is captured. Right now, I have a blanket "standalones" exception. I'm considering putting one on the tempdownload folder as well, but I'll need to modify the debloat to enable Defender with these exclusions to confirm I'm not missing anything.

**Comment by digitalsleuth** [comment]
So I did some testing and modified the debloat and states appropriately and everything seems to work well. Thanks for bringing this up!

**Comment by angry-bender** [comment]
> So I did some testing and modified the debloat and states appropriately and everything seems to work well. Thanks for bringing this up!

That's awesome, no worries at all 🙂.
